### ISSUE TITLE
Add unpapulated QSPI RAM footprint

### ISSUE THREAD

**Issue by esden** [icebreaker-fpga/icebreaker#19]
To add expanded RAM amount to the iCEBreaker without sacrificing the PMODs we should have an SO8 unpopulated/optional footprint for the LY68L6400.

We can think about a better setup for this in the V2.0 hardware cycle.

**Comment by esden** [comment]
As per @smunaut suggestion. I have added a pad that allows for an easy addition of an SPI RAM chip in SO8 package piggybacked onto the existing flash chip. We can't use ram and flash at the same time but we can use them in the same design by using ~LEDG signal as CS for the RAM. It is good enough for V1.0 ;)

**Comment by umarcor** [comment]
@esden, I can't identify that pad in the schematics or the figures in the readme. Was it removed in the end?

**Comment by smunaut** [comment]
Next to pin 37 of the fpga in https://github.com/icebreaker-fpga/icebreaker/blob/master/hardware/v1.0e/icebreaker-sch.pdf

**Comment by umarcor** [comment]
@smunaut thanks. I misunderstodd the meaning of "piggybacked" and I was looking for an unpopulated footprint at the bottom. All clear now.

**Comment by esden** [comment]
@umarcor Right, it might not be clear for everyone. I am putting a photo of how it comes together for reference.

![DSC_2070](https://user-images.githubusercontent.com/17334/102542532-cfad1200-4066-11eb-90ea-c0932e934e4e.jpeg)
