### ISSUE TITLE
"J20 Flash" header - add single-row PMOD option?

### ISSUE THREAD

**Issue by fm4dd** [icebreaker-fpga/icebreaker#40]
Would it be possible to re-arrange the "J20 Flash" header? Shift IO0-3 pins two positions right, add a 3.3 pad next to SCK, and move GND left would give one more single-row PMOD option. I haven't fully checked the board design yet, here is a quick picture of what I mean:

![icebreaker-j20-enhance](https://user-images.githubusercontent.com/1367011/73129623-b43eb000-402b-11ea-8600-2309a9692b25.jpg)

Moving CS / SCK to the outer-right, and using their pads as 3.3 / GND would also achieve it.

**Comment by fm4dd** [comment]
Never mind, I looked at the schematics. The pins are FTDI IO and not FPGA. All FPGA pins are already brought out.

**Comment by esden** [comment]
You are partly correct though. These IO pins go to the FLASH and after the FPGA is configured they could theoretically be used to talk to another device. You just have to be "careful" what you are connecting and how.

The actual issue that I would have with changing the pin order is backwards compatibility. There are plans to make hats for the iCEBreaker that connect to different pins to implement a variety of different features using more than just two Pmod. Changing the position and layout of the pins is pretty much out of the question unless it can be left backwards compatible to the current layout.
