### ISSUE TITLE
FPGA Pin numbers of SPI IO0/IO1 on the diagram are swapped

### ISSUE THREAD

**Issue by smunaut** [icebreaker-fpga/icebreaker#41]
The pinout on https://raw.githubusercontent.com/icebreaker-fpga/icebreaker/master/img/icebreaker-v1_0b-legend.jpg is wrong for the SPI header.  FPGA pin number for IO0 and IO1 are swapped.

**Comment by mcerveny** [comment]
I depends on soldered jumpers.
![image](https://user-images.githubusercontent.com/1438115/211793874-58d028d5-de18-4d85-a140-ad715146183d.png)

**Comment by smunaut** [comment]
Yes, obviously but it makes sense to reflect the default configuration. Anyone doing manual alteration on the board has to know what they're doing ...
