### ISSUE TITLE
outdated RGBPanel link on https://www.crowdsupply.com/1bitsquared/icebreaker-fpga

### ISSUE THREAD

**Issue by marcmerlin** [icebreaker-fpga/icebreaker#51]
In "This impressive flexible design by Sylvain Munaut (a.k.a. tnt)"
please replace
https://github.com/smunaut/icebreaker-temp/tree/master/rgb_panel
with
https://github.com/smunaut/ice40-playground/tree/master/projects/rgb_panel

I have tested that code with my icebreaker, and it works as of today

**Comment by esden** [comment]
Thank you very much for reporting this. I have corrected it, and it should go live on the website in a few days when CS processes my change. :)
